/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangNovostiIndexRouteImport } from './routes/$lang/novosti/index'
import { Route as LangNovostiSlugRouteImport } from './routes/$lang/novosti/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangNovostiIndexRoute = LangNovostiIndexRouteImport.update({
  id: '/novosti/',
  path: '/novosti/',
  getParentRoute: () => LangRoute,
} as any)
const LangNovostiSlugRoute = LangNovostiSlugRouteImport.update({
  id: '/novosti/$slug',
  path: '/novosti/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/novosti/$slug': typeof LangNovostiSlugRoute
  '/$lang/novosti/': typeof LangNovostiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/novosti/$slug': typeof LangNovostiSlugRoute
  '/$lang/novosti': typeof LangNovostiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/novosti/$slug': typeof LangNovostiSlugRoute
  '/$lang/novosti/': typeof LangNovostiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/'
    | '/$lang/novosti/$slug'
    | '/$lang/novosti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/sitemap.xml' | '/$lang' | '/$lang/novosti/$slug' | '/$lang/novosti'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/'
    | '/$lang/novosti/$slug'
    | '/$lang/novosti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/novosti/': {
      id: '/$lang/novosti/'
      path: '/novosti'
      fullPath: '/$lang/novosti/'
      preLoaderRoute: typeof LangNovostiIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/novosti/$slug': {
      id: '/$lang/novosti/$slug'
      path: '/novosti/$slug'
      fullPath: '/$lang/novosti/$slug'
      preLoaderRoute: typeof LangNovostiSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangNovostiSlugRoute: typeof LangNovostiSlugRoute
  LangNovostiIndexRoute: typeof LangNovostiIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangNovostiSlugRoute: LangNovostiSlugRoute,
  LangNovostiIndexRoute: LangNovostiIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
